name: demoproject
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  badges: ^2.0.2
  provider: ^6.0.2
  http: ^0.13.4
  google_fonts: ^2.3.1
  iconsax: ^0.0.8
  ms_undraw: ^3.1.0+2
  flutter_markdown: ^0.6.9+1
  markdown_editable_textinput: ^2.0.2
  rflutter_alert: ^2.0.4
  localization: ^2.1.0
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  shared_preferences: ^2.0.13
  time_machine: ^0.9.16
  file_picker: ^4.5.1
  open_file: ^3.2.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
